Repository RIOT-OS/RobotFW-tests, pull requests merged in 2019-11, with the labels that each got.

#38 tests/periph_gpio: Add periph gpio test for debug pin checks
  tests/periph_gpio/Makefile
  tests/periph_gpio/main.c
  tests/periph_gpio/tests/01__periph_gpio_base.robot
  tests/periph_gpio/tests/GPIOdevice.py
  tests/periph_gpio/tests/periph_gpio.keywords.txt
  tests/periph_gpio/tests/periph_gpio_if.py
Labels: enhancement

#35 tests/periph_timer: fix resets in test setup
  tests/periph_timer/tests/01__periph_timer_base.robot
  tests/periph_timer/tests/02__periph_timer_extra.robot
  tests/periph_timer/tests/03__periph_timer_set_delays.robot
Labels: bug, enhancement

#43 tests/common/test_helpers: Fix printf casting
  tests/common/test_helpers.c
Labels: bug

#41 tests/periph_uart: Expose uart dev and clean
  tests/periph_uart/Makefile
  tests/periph_uart/tests/01__periph_uart_base.robot
  tests/periph_uart/tests/02__periph_uart_mode.robot
  tests/periph_uart/tests/periph_uart.keywords.txt
  tests/periph_uart/tests/periph_uart_if.py
Labels: enhancement

#42 dist/tools: Add tool to print current setup
  Jenkinsfile
  dist/tools/ci/print_environment.py
  dist/tools/ci/print_environment.sh
Labels: enhancement

#45 dist/tools/ci: Fix script naming for print env
  dist/tools/ci/print_environment.sh
Labels: bug

#44 common: move test helpers and add args parse helpers
  tests/Makefile.tests_common
  tests/periph_i2c/main.c
  tests/periph_timer/main.c
  tests/periph_uart/main.c
  utils/common/Makefile
  utils/common/Makefile.include
  utils/common/include/test_helpers.h
  utils/common/test_helpers.c
  utils/sc_args/Makefile
  utils/sc_args/Makefile.include
  utils/sc_args/include/sc_args.h
  utils/sc_args/sc_args.c
Labels: enhancement

#47 fix(periph_timer): Fix casting issues in periph timer
  tests/periph_timer/main.c
Labels: bug

#48 tests/periph_timer: Fix arg check of some timer calls
  tests/periph_timer/main.c
Labels: bug

#49 tests/timer:Fix gpio_init call in cmd_timer_debug_pin
  tests/periph_timer/main.c
Labels: bug

#46 feat(conf): Add board default pin configuration
  dist/etc/conf/arduino-due.env
  dist/etc/conf/arduino-mega2560.env
  dist/etc/conf/arduino-mkrzero.env
  dist/etc/conf/default.env
  dist/etc/conf/esp32-wroom-32.env
  dist/etc/conf/frdm-k22f.env
  dist/etc/conf/frdm-k64f.env
  dist/etc/conf/frdm-kw41z.env
  dist/etc/conf/nrf52dk.env
  dist/etc/conf/nucleo-f091rc.env
  dist/etc/conf/nucleo-f103rb.env
  dist/etc/conf/nucleo-f411re.env
  dist/etc/conf/nucleo-f767zi.env
  dist/etc/conf/nucleo-l073rz.env
  dist/etc/conf/remote-revb.env
  dist/etc/conf/saml10-xpro.env
  dist/etc/conf/samr21-xpro.env
  dist/etc/conf/samr30-xpro.env
  dist/etc/conf/slstk3401a.env
  dist/etc/conf/slstk3402a.env
  dist/robotframework/res/riot_base.keywords.txt
  tests/Makefile.tests_common
  tests/README.md
  tests/periph_gpio/Makefile
  tests/periph_gpio/tests/01__periph_gpio_base.robot
  tests/periph_gpio/tests/periph_gpio.keywords.txt
  tests/periph_i2c/Makefile
  tests/periph_i2c/tests/periph_i2c.keywords.txt
  tests/periph_timer/Makefile
  tests/periph_timer/README.md
  tests/periph_timer/tests/01__periph_timer_base.robot
  tests/periph_timer/tests/02__periph_timer_extra.robot
  tests/periph_timer/tests/periph_timer.keywords.txt
  tests/periph_uart/Makefile
  tests/periph_uart/tests/periph_uart.keywords.txt
  tests/xtimer_cli/Makefile
  tests/xtimer_cli/tests/01__xtimer_base.robot
Labels: enhancement
